# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [29]:
print(np.__version__)
print(np.show_config())

2.1.0
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30154",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.11",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30154",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.27",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-ofdn91k7/cp310-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib 

c:\Personal\DA DS\Projects for Portofolio\100-Numpy-Puzzles\venv\lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


#### 3. Create a null vector of size 10 (★☆☆)

In [7]:
vec3 = np.zeros(10)
vec3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [10]:
vec3_memory = vec3.size*vec3.itemsize
vec3_memory

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [4]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
vec6 = np.zeros(10)
vec6[4] = 1
vec6

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
vec7 = np.arange(10, 50)
vec7

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
vec8 = np.arange(1, 5)
print("Original vector", vec8)
reversed_vec8 = vec8[::-1]
print("Reversed original vector", reversed_vec8)

Original vector [1 2 3 4]
Reversed original vector [4 3 2 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [14]:
mat9 = np.arange(0, 9).reshape(3, 3)
mat9

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [17]:
vec10 = [1, 2, 0, 0, 4, 0]
vec10_ = np.array(vec10)
index_0 = np.where(vec10_==0)
index_0

(array([2, 3, 5]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [18]:
mat11 = np.eye(3)
mat11

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [22]:
arr12 = np.random.rand(3, 3, 3)
arr12

array([[[0.76135822, 0.08974138, 0.71913547],
        [0.59497894, 0.04144409, 0.8857475 ],
        [0.93791252, 0.14889672, 0.69638159]],

       [[0.62460311, 0.93336794, 0.11371215],
        [0.50728089, 0.87397012, 0.4197481 ],
        [0.07568731, 0.68503837, 0.05971775]],

       [[0.25976083, 0.72701613, 0.61069003],
        [0.24950352, 0.67764945, 0.38424056],
        [0.85003655, 0.59952509, 0.53594557]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [24]:
arr13 = np.random.rand(10, 10)
print("Array :", arr13)
print("Minimum value of array :", arr13.min()) 
print("Maximum value of array : ", arr13.max())

Array : [[0.64543894 0.53368273 0.71335719 0.30172807 0.57633245 0.18087674
  0.00226111 0.41258183 0.04148339 0.59895972]
 [0.57987743 0.7957882  0.98772308 0.17879416 0.47193466 0.53998642
  0.54304714 0.23497576 0.10498235 0.09367634]
 [0.74845184 0.58601711 0.42261662 0.51485579 0.21236594 0.55559112
  0.53684466 0.54259616 0.62764325 0.50005146]
 [0.9538377  0.20519041 0.71241825 0.80252995 0.85377255 0.01339597
  0.70827147 0.46409247 0.75734153 0.59273352]
 [0.80560036 0.01284407 0.44284712 0.22859241 0.78742889 0.55957322
  0.21262012 0.66911807 0.45200712 0.43425929]
 [0.22924298 0.22090377 0.25908153 0.30737818 0.3537578  0.01556701
  0.78033962 0.44237195 0.8433855  0.05220352]
 [0.57139121 0.09381505 0.12173806 0.2675357  0.01283654 0.98717355
  0.54196266 0.73391534 0.62752833 0.21046882]
 [0.57799007 0.17769443 0.19652003 0.58950025 0.42495125 0.88647352
  0.32203944 0.45677384 0.81911157 0.82322345]
 [0.26243642 0.27783006 0.24546194 0.27845733 0.37995073 0.73096428
  0.

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [9]:
vec14 = np.random.rand(30)
print(np.mean(vec14))

0.5883694072885234


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [13]:
arr15 = np.array([[0, 0], [0, 0]])
bordered_arr15 = np.pad(arr15, pad_width=1, mode='constant', constant_values=1)
bordered_arr15

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [12]:
arr16 = np.array([[1, 1], [2, 2]])
bordered_arr16 = np.pad(arr16, pad_width=1, mode='constant', constant_values=0)
bordered_arr16

array([[0, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 2, 2, 0],
       [0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [2]:
list_17 = [0 * np.nan, np.nan == np.nan, np.inf > np.nan, np.nan - np.nan, np.nan in set([np.nan]), 0.3 == 3 * 0.1]
list_17

[nan, False, False, nan, True, False]

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [11]:
mat18 = np.eye(5)
mat18[1][0] = 1
mat18[2][1] = 2
mat18[3][2] = 3
mat18[4][3] = 4
mat18

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 2., 1., 0., 0.],
       [0., 0., 3., 1., 0.],
       [0., 0., 0., 4., 1.]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [12]:
mat19 = np.zeros((8,8), dtype=int)

mat19[1::2, ::2] = 1
mat19[::2, 1::2] = 1
mat19

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [8]:
# D for dark and L for light
odd_row = np.array([['L', 'D']])
even_row = np.array([['D', 'L']])
checker21 = np.tile(np.vstack((odd_row, even_row)) , (4, 4))
print(checker21) 

[['L' 'D' 'L' 'D' 'L' 'D' 'L' 'D']
 ['D' 'L' 'D' 'L' 'D' 'L' 'D' 'L']
 ['L' 'D' 'L' 'D' 'L' 'D' 'L' 'D']
 ['D' 'L' 'D' 'L' 'D' 'L' 'D' 'L']
 ['L' 'D' 'L' 'D' 'L' 'D' 'L' 'D']
 ['D' 'L' 'D' 'L' 'D' 'L' 'D' 'L']
 ['L' 'D' 'L' 'D' 'L' 'D' 'L' 'D']
 ['D' 'L' 'D' 'L' 'D' 'L' 'D' 'L']]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [13]:
mat22 = np.random.rand(5, 5) 

# nomralize using L2 norm
mat22_normalized = mat22/np.linalg.norm(mat22)
mat22_normalized

array([[0.15844542, 0.20269726, 0.23297632, 0.18372988, 0.11889494],
       [0.19688333, 0.03033597, 0.27353837, 0.1177159 , 0.03304753],
       [0.18637034, 0.27122757, 0.1425361 , 0.09593827, 0.28167737],
       [0.15041881, 0.20696321, 0.00174192, 0.36479347, 0.25735138],
       [0.09069513, 0.24687719, 0.30058484, 0.00578812, 0.24636564]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [14]:
num23_dtype = np.dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])
data23 = np.array([
    (255, 0, 0, 255),
    (0, 255, 0, 128),
    (0, 0, 255, 64)],
    dtype=num23_dtype)

print(data23)

[(255,   0,   0, 255) (  0, 255,   0, 128) (  0,   0, 255,  64)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [17]:
mat24_a = np.random.rand(5, 3)
mat24_b = np.random.rand(3, 2)
mat24_ = mat24_a @ mat24_b
print("First matrix : ", mat24_a, "\n")
print("Second matrix : ", mat24_b, "\n")
print("Result of matrix multiplication : ", mat24_)

First matrix :  [[0.67349155 0.85352975 0.70967513]
 [0.25599629 0.06637315 0.1645999 ]
 [0.15481289 0.93339017 0.91443954]
 [0.19675005 0.3931933  0.28777199]
 [0.95226981 0.57376367 0.91440242]] 

Second matrix :  [[0.76179554 0.78490841]
 [0.00339979 0.61651536]
 [0.19203519 0.63135729]] 

Result of matrix multiplication :  [[0.65224728 1.50290195]
 [0.22685146 0.34577506]
 [0.29671367 1.27430139]
 [0.20648243 0.57852742]
 [0.90298302 1.67849334]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [18]:
arr25 = np.arange(1, 16)
arr25_ = arr25.copy()
arr25_[(arr25_>3) & (arr25_<8)] *= -1
print("Original array : ", arr25, "\n")
print("Negated array : ", arr25_)

Original array :  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] 

Negated array :  [ 1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14 15]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [19]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [26]:
Z = np.array([100, 200, 300])
print(Z**Z) 
print(2<<Z>>2) 
print(Z <- Z) 
print(1j*Z) 
print(Z/1/1) 
print(Z<Z>Z)

[0 0 0]
[0 0 0]
[False False False]
[0.+100.j 0.+200.j 0.+300.j]
[100. 200. 300.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [27]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


C:\Users\ASUS\AppData\Local\Temp\ipykernel_5148\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5148\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\ASUS\AppData\Local\Temp\ipykernel_5148\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [28]:
# Answer : Using function from numpy library, np.cell() for positive number and np.floor() for negative number

arr29 = np.array([1.2, -1.2, 2.5, -2.5, 3.7, -3.7])
round_away_from_zero = np.where(arr29>0, np.ceil(arr29), np.floor(arr29))
print("Original array :", arr29, "\n")
print("Rounded away from zero array : ", round_away_from_zero)

Original array : [ 1.2 -1.2  2.5 -2.5  3.7 -3.7] 

Rounded away from zero array :  [ 2. -2.  3. -3.  4. -4.]


#### 30. How to find common values between two arrays? (★☆☆)

In [32]:
arr30_a = np.array([1, 2, 3, 4])
arr30_b = np.array([3, 4, 5, 6])
print(np.intersect1d(arr30_a, arr30_b))

[3 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
import warnings 

warnings.filterwarnings('ignore', module='numpy')

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [33]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


C:\Users\ASUS\AppData\Local\Temp\ipykernel_5148\2770867030.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [36]:
print("Date today : ", np.datetime64("today", "D"))
print("Date yesterday :", np.datetime64("today",  "D") - np.timedelta64(1, "D"))
print("Date tomorrow :", np.datetime64("today",  "D") + np.timedelta64(1, "D"))

Date today :  2024-09-08
Date yesterday : 2024-09-07
Date tomorrow : 2024-09-09


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [37]:
np.arange("2016-07", "2016-08", dtype="datetime64[D]")

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [8]:
matrix37 = np.tile(np.arange(5), (5,1))
matrix37

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [15]:
def gen_10int(n) -> np.array:
    list_ = []
    for i in range(n):
        list_.append(np.random.randint(1, 20,1))
    return list_    

arr38 = gen_10int(10)
arr38

[array([2], dtype=int32),
 array([19], dtype=int32),
 array([19], dtype=int32),
 array([16], dtype=int32),
 array([17], dtype=int32),
 array([6], dtype=int32),
 array([17], dtype=int32),
 array([13], dtype=int32),
 array([10], dtype=int32),
 array([11], dtype=int32)]

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [6]:
vec39 = np.linspace(start=0, stop=1, num=12)[1:-1]
vec39

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [10]:
vec40 = np.random.rand(10)
print("Original array : ", vec40)
print("Sorted array : ", np.sort(vec40))

Original array :  [0.91560018 0.20007559 0.0644359  0.71249678 0.05265318 0.75882017
 0.94121857 0.17216592 0.96381179 0.49551391]
Sorted array :  [0.05265318 0.0644359  0.17216592 0.20007559 0.49551391 0.71249678
 0.75882017 0.91560018 0.94121857 0.96381179]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [12]:
# exmaple of small array is array of 10 elements
import time

arr41 = np.random.rand(10)

# first method using np sum
start1 = time.time()
np.sum(arr41)
end1 = time.time()
print(f"Np.sum method completed in : {end1-start1} s")

# second method using np sum
start2 = time.time()
arr41.sum()
end2 = time.time()
print(f"Np.ndarray.sum method completed in : {end2-start2} s")

Np.sum method completed in : 0.00099945068359375 s
Np.ndarray.sum method completed in : 0.0 s


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [13]:
arr42_A = np.random.rand(5)
arr42_B = np.random.rand(5)
np.array_equal(arr42_A, arr42_B)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [14]:
# using flags writable attribute to make an array immutable
arr43 = np.random.rand(5)
arr43.flags.writeable = False

# try to change one of the element
arr43[2] = 19


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [19]:
mat44 = np.random.rand(20).reshape(10, 2)
x_44 = mat44[:, 0]
y_44 = mat44[:, 1]
r_44 = np.sqrt(x_44**2+y_44**2)
a_44 = np.arctan2(x_44, y_44)
print("Cartesian coordinates : ", mat44, "\n")
print("Cartesian coordinates converted to Polar : ", np.stack((r_44, a_44), axis=1))

Cartesian coordinates :  [[0.69281303 0.60007414]
 [0.85083252 0.85576681]
 [0.86152816 0.86302198]
 [0.45030819 0.85845093]
 [0.11292707 0.67900951]
 [0.54257607 0.50049123]
 [0.37764228 0.4896629 ]
 [0.34294205 0.54737952]
 [0.53771114 0.3466235 ]
 [0.63164418 0.41112   ]] 

Cartesian coordinates converted to Polar :  [[0.91655816 0.8570056 ]
 [1.206753   0.78250688]
 [1.21944156 0.78453195]
 [0.96938922 0.48310125]
 [0.688336   0.16480307]
 [0.73816005 0.82572349]
 [0.61837161 0.65694988]
 [0.64593621 0.55968876]
 [0.63975083 0.99820703]
 [0.75365378 0.9938078 ]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [25]:
vec45 = np.random.rand(10)
print("Original vector : ", vec45)
max45_i = np.where(vec45==vec45.max())
vec45[max45_i] = 0
print("Modified vector : ", vec45)

Original vector :  [0.66917479 0.42251546 0.72617165 0.74728904 0.03066878 0.46161986
 0.13680647 0.18276798 0.43534754 0.24363088]
Modified vector :  [0.66917479 0.42251546 0.72617165 0.         0.03066878 0.46161986
 0.13680647 0.18276798 0.43534754 0.24363088]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [31]:
dtype_46 = [('vert_axis', 'U10'), ('horz_axis', 'O')]
arr46 = np.array([('x', np.random.uniform(0, 1, 10)), 
                  ('y', np.random.uniform(0, 1, 10))],
                 dtype=dtype_46)
arr46

array([('x', array([0.99069982, 0.5731802 , 0.70677029, 0.09362304, 0.34152429,
              0.10005926, 0.74653133, 0.30179492, 0.77062894, 0.1909348 ]))    ,
       ('y', array([0.37396311, 0.44949568, 0.52261372, 0.53835933, 0.10848543,
              0.13213627, 0.96960877, 0.36207995, 0.51680927, 0.1623695 ]))    ],
      dtype=[('vert_axis', '<U10'), ('horz_axis', 'O')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)